---
version: '3'

services:
  flask:
    container_name: flask_api
    hostname: flask_api
    image: flask-api
    profiles:
      - api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      minio:
        condition: service_healthy
      schema-registry:
        condition: service_healthy
      kafka-broker:
        condition: service_healthy
    ports:
      - 5000:5000
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    volumes:
      - ${PROJECT_DIR:-${PWD}}/src/flask_api:/flask_api

  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    hostname: minio
    profiles:
      - minio
    environment:
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: password
      # MINIO_CONFIG_ENV_FILE: /etc/config.env
      # MINIO_SERVER_URL: https://minio.example.net:9000
      # MINIO_BROWSER_REDIRECT_URL: https://example.net/minio/ui
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:9001/health"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ${PROJECT_DIR:-${PWD}}/src/docker/minio/data:/data
    command: server /data --console-address :9001
    restart: always

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    profiles:
      - kafka
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181     # Instructs ZooKeeper where to listen for connections by clients such as Apache Kafka
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_TICK_TIME: 2000
    healthcheck:
      test: [ "CMD", "bash", "-c", "echo 'ruok' | nc localhost 2181" ]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always

  # docs: https://docs.confluent.io/platform/current/kafka/multi-node.html
  # KAFKA_ZOOKEEPER_CONNECT: Instructs Kafka how to get in touch with ZooKeeper.
  # KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: Defines key/value pairs for the security protocol to use, per listener name
  # KAFKA_INTER_BROKER_LISTENER_NAME: Defines which listener to use for inter-broker communication. Kafka brokers communicate between themselves, usually on the internal network
  kafka-broker:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka-broker
    hostname: kafka-broker
    profiles:
      - kafka
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: DOCKER://kafka-broker:19092,DOCKER_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: DOCKER:PLAINTEXT,DOCKER_HOST:PLAINTEXT  # PLAINTEXT means no security
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: [ "CMD", "bash", "-c", "nc -z localhost 9092" ]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always

  schema-registry:
    image: confluentinc/cp-schema-registry:7.5.0
    container_name: schema-registry
    hostname: schema-registry
    profiles:
      - kafka
    ports:
      - "8081:8081"
    # depends_on:
    #   kafka-broker:
    #     condition: service_healthy
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka-broker:19092
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
    healthcheck:
      test: [ "CMD", "curl", "--output", "/dev/null", "--silent", "--head", "--fail", "http://schema-registry:8081/subjects" ]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: always

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    profiles:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: PLAINTEXT://kafka-broker:19092,PLAINTEXT_HOST://kafka-broker:19092
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schema-registry:8081
      # KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: kafka-connect
      # KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: http://kafka-connect:8083
      DYNAMIC_CONFIG_ENABLED: 'true'
    ports:
      - 8889:8080  # host: image
    depends_on:
      kafka-broker:
        condition: service_healthy
      schema-registry:
        condition: service_healthy
      # kafka-connect:
      #   condition: service_completed_successfully
    restart: always
